@startuml
skinparam linetype ortho
skinparam packageStyle rectangle
left to right direction

Actor Client

rectangle sucre {
    Client -> (Ajouter sucre)
    Client -> (Enlever sucre)
}
rectangle commande {
    Client -> (Commander boisson)
    (Commander café long) .> (Commander boisson) : extends
    (Commander café court) .> (Commander boisson) : extends
    (Commander café verre d'eau) .> (Commander boisson) : extends
}
rectangle monnayeur {
    Client -> (Inserer pièce)
    Client -> (Rendre la monnaie)
}
@enduml